config/routes.rb
Matrix::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  resources :devices
  resources :imports
  resources :examinations

  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/imprint', to: 'static_pages#imprint', via: 'get'
  match '/advantages', to: 'static_pages#advantages', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
  has_many :imports
  default_scope -> { order('created_at DESC') }

  validates :user_id, presence: true
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :signed_in_user
  before_action :correct_device,         only: [:show,:edit, :update, :destroy]

  def index
    @devices = Device.where(user: current_user).paginate(page: params[:page])
  end

  def new
    @device = Device.new
  end

  def show
  end

  def create
    @device = Device.new(device_params)
    @device.user = current_user
    if @device.save
      flash[:success] = "Gerät angelegt!"
      redirect_to devices_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @device.update_attributes(device_params)
      flash[:success] = "Änderungen gespeichert."
      redirect_to devices_path
    else
      render 'edit'
    end
  end

  def destroy
    @device.destroy
    flash[:success] = "Gerät wurde gelöscht."
    redirect_to devices_path
  end

  private

  def device_params
    params.require(:device).permit(:inventory_no, :serial_no, :location, :kind, :type, :vendor)
  end

  # Before filters

  def correct_device
    @device = Device.find(params[:id])
    redirect_to root_url unless current_user?(@device.user)
  end

end

app/views/devices/_device.html.erb
<li>
  <%= device.inventory_no  %> | <%= link_to device.kind, device %> | <%= link_to "Löschen", device, method: :delete, data: { confirm: "Wirklich löschen?" } %>
</li>

app/views/devices/_fields.html.erb
<%= render 'shared/error_messages_devices' %>

<div class="control-group">
  <div class="controls">
    <%= f.label :Inventarnummer%>
    <%= f.number_field :inventory_no %>
  </div>
  <div class="controls">
    <%= f.label :Geräteart %>
    <%= f.text_field :kind %>
  </div>
  <div class="controls">
    <%= f.label :Standort %>
    <%= f.text_field :location %>
  </div>
  <div class="controls">
    <%= f.label :Hersteller %>
    <%= f.text_field :vendor %>
  </div>
  <div class="controls">
    <%= f.label :Typ %>
    <%= f.text_field :type_no%>
  </div>
  <div class="controls">
    <%= f.label :Seriennummer %>
    <%= f.text_field :serial_no %>
  </div>
</div>

app/views/devices/edit.html.erb
<% provide(:title, "Prüfbericht anpassen") %>
<h1>Prüfbericht anpassen</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@device) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Speichern", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/devices/index.html.erb
<% provide(:title, 'Meine Geräte') %>

<h1>Meine Geräte</h1>


<%= will_paginate %>

<ul class="paginationlist">
  <%= render @devices %>
</ul>

<%= will_paginate %>

app/views/devices/new.html.erb
<% provide(:title, "Gerät anlegen") %>
<h1>Gerät anlegen<h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@device) do |f| %>
      <%= render 'fields', f: f %>
      <div class="form-actions">
	<%= f.submit "Gerät anlegen", class: "btn btn-primary" %>
      </div>
      <% end %>
  </div>
</div>

app/views/devices/show.html.erb
<% provide(:title, "Gerätedetails") %>

<h2>Gerätedetails</h2>

<p>
  Inventarnummer:  <%= @device.inventory_no %>
</p>
<p>
    Geräteart:  <%= @device.kind %>
</p>
<p>
    Standort:  <%= @device.location%>
</p>
<p>
    Hersteller:  <%= @device.vendor %>
</p>
<p>
  Typ:    <%= @device.type_no%>
</p>
<p>
  Seriennummer:  <%= @device.serial_no%>
</p>

<%= link_to "Gerät anpassen", edit_device_path(@device), class: "btn btn-primary pull-right" %>