config/routes.rb
Matrix::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  resources :devices
  resources :imports
  resources :examinations

  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/imprint', to: 'static_pages#imprint', via: 'get'
  match '/advantages', to: 'static_pages#advantages', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :device
  belongs_to :user
  has_attached_file :import_file

  default_scope -> { order('created_at DESC') }
  validates :device_id, presence: true
  validates :user_id, presence: true
  validates_attachment_content_type :import_file, :content_type => ["text/xml", "text/plain"]
  validates_attachment :import_file, :presence => true,
                       :size => {:less_than => 10.megabytes}

  before_save :parse_file

  private

  def parse_file
    tempfile = import_file.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_element(node)
    end
  end

  def parse_element(node)
  end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :admin_user
  before_action :correct_import, only: [:show, :edit, :destroy]

  def index
    @imports = Import.where(user: current_user).paginate(page: params[:page])
  end

  def new
    @import = Import.new
  end

  def show
  end

  def create
    @import = Import.new(import_params)
    @import.user = current_user
    if @import.save
      flash[:success] = "Prüfbericht angelegt!"
      redirect_to imports_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @import.update_attributes(import_params)
      flash[:success] = "Änderungen gespeichert."
      redirect_to imports_path
    else
      render 'edit'
    end
  end

  def destroy
    @import.destroy
    flash[:success] = "Import wurde gelöscht."
    redirect_to imports_url
  end

  private

  def import_params
    params.require(:import).permit(:import_file)
  end

    # Before filters

    def correct_import
      @import = Import.find_by_id(params[:id])
      redirect_to root_url unless @import != nil && current_user?(@import.user)
    end
end

app/views/imports/_fields.html.erb
<%= render 'shared/error_messages_imports' %>

<div class="control-group">
  <div class="controls">
    <%= f.label :import_file, 'Datei auswählen'%>
    <%= f.file_field :import_file %>
  </div>
</div>

app/views/imports/_import.html.erb
<li>
  <%= link_to import.id, import %> | <%= link_to "Löschen", import, method: :delete, data: { confirm: "Wirklich löschen?" } %>
</li>

app/views/imports/edit.html.erb
<% provide(:title, "Import anpassen") %>
<h1>Import anpassen</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@import) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Import anpassen", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/imports/index.html.erb
<% provide(:title, 'Meine Imports') %>

<%= link_to "Import hochladen", new_import_path, class: "btn btn-primary pull-right" %>

<h1>Meine Imports</h1>


<%= will_paginate %>

<ul class="paginationlist">
  <%= render @imports %>
</ul>

<%= will_paginate %>

app/views/imports/new.html.erb
<% provide(:title, "Import hochladen") %>
<h1>Import hochladen</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@import) do |f| %>
      <%= render 'fields', f: f %>
      <div class="form-actions">
	<%= f.submit "Import hochladen", class: "btn btn-primary" %>
      </div>
      <% end %>
  </div>
</div>

app/views/imports/show.html.erb
<% provide(:title, "Import anzeigen") %>
<%= @import.import_file %>