config/routes.rb
Matrix::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  resources :devices
  resources :imports
  resources :examinations

  root 'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/imprint', to: 'static_pages#imprint', via: 'get'
  match '/advantages', to: 'static_pages#advantages', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <small>
      Quality made in Germany.
    </small>
    <nav>
      <ul>
        <li><%= link_to "Hilfe", help_path %></li>
        <li><%= link_to "Über uns", about_path %></li>
        <li><%= link_to "Kontakt", contact_path %></li>
        <li><%= link_to "Impressum", imprint_path %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Power.Check", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
              <% if current_user.admin? %>
                  <li><%= link_to "Nutzer", users_path %></li>
                  <li><%= link_to "Imports", imports_path %></li>
              <% end %>
              <li><%= link_to "Inventar", devices_path %></li>
              <li><%= link_to "Prüfberichte", examinations_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profil", current_user %></li>
                  <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout", signout_path, method: "delete" %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Warum Power.Check?", advantages_path %></li>
              <li><%= link_to "Login", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>